### ISSUE TITLE
Uncap framerate?

### ISSUE THREAD

**Issue by ROCKNROLLKID** [raa-eruanna/qzdoom#10]
Sorry if this is the wrong place to suggest this, but could QZDoom have an option to uncap framerate. I notice a lot of lag with QZDoom and I think uncapping the framerate much solve some of the lag. This is what prboom plus did with their fork and it actually is quite nice to play with 60+ fps.

**Comment by raa-eruanna** [comment]
QZDoom presently does uncap the framerate. If you are getting a stuttered frame rate it is a hardware/driver/speed issue. 

If you are using r_polyrenderer, then your CPU may be too slow to support it smoothly. (r_dynlights may cause speed issues, too)

If you are using Intel/NVidia Optimus, either use your integrated (Intel) adapter, or switch to fullscreen mode. There is a known issue in Windows 10 with the windowing environment that prevents applications from frame syncing properly.

Right now the only officially supported modes in QZDoom are the palette renderer, truecolor renderer, and OpenGL.

**Comment by ROCKNROLLKID** [comment]
Na I don't have Nvidia or Intel. All AMD here. I use OpenGL for render. GZDoom runs fine without lag for me in OpenGL. I noticed the upscaling feature in truecolor settings causes most of the lag. Disabling it helps, but I still get lags at times. I mean I have a RX480 and a fx6200 processor. It should be able to play this just fine. I am using the latest 16.12.2 drivers from AMD and I have already done a clean install of it recently. Any other suggestions?

Maybe adding options to use 24 bit coloring or 16 bit coloring instead of 32bit might help, too. That way it is more the 8 bit, but not as laggy as 32 bit.

**Comment by raa-eruanna** [comment]
Try running at a lower resolution. I'm guessing you're using ultra-hidef modes with that kind of hardware - but it's important to keep in mind that QZDoom is a software renderer - and even a 6x3.8GHz can choke on it at 4k+ resolutions.

**Comment by dpjudas** [comment]
But the way, if you're using the GL renderer, then for all points and purposes QZDoom is IS GZDoom. If you're getting different performance, it has to be a different setting somewhere in your ini file. The code running the show is identical.

**Comment by ROCKNROLLKID** [comment]
I switched from 4K to 1440p and it solved the lag issues. Any idea why I can play GZDoom port on 4K perfectly fine, but not this? The only thing different in settings is truecolor.

**Comment by raa-eruanna** [comment]
GZDoom acts a lot more hardware than just your CPU. Your GPU (in OpenGL mode) can handle the extra resolution a lot easier, especially being a newer one. The CPU, despite how fast it is, is still facing bottlenecking issues from the Truecolor code - as I said, that's software rendering. The wider your screen is, the more it has to calculate. And unfortunately, some portion of it is still being done on a single core, so even a sextuple-core CPU is going to have issues. However, your CPU can still handle quite a bit more than the average CPU can, so you can still run higher resolutions than everything else - but until all the problems in the software rendering code are fixed, these bottleneck issues will continue to be a problem.

**Comment by ROCKNROLLKID** [comment]
Thanks for your help. What about my other suggestion, to use 24-bit or 16-bit colors instead of 32-bit? That might be a good temporary solution for now until real fixes come along.

**Comment by raa-eruanna** [comment]
This was already asked before and [No]'d. Besides, with where the code is being bottlenecked, I doubt that it will help any. It's not the drawing that is the issue, it's calculating the geometry on the screen.
